BEGIN;

TRUNCATE TABLE "payments" CASCADE;
TRUNCATE TABLE "booking_games" CASCADE;
TRUNCATE TABLE "bookings" CASCADE;
TRUNCATE TABLE "booking_rates" CASCADE;
TRUNCATE TABLE "games_categories" CASCADE;
TRUNCATE TABLE "game_images" CASCADE;
TRUNCATE TABLE "games" CASCADE;
TRUNCATE TABLE "categories" CASCADE;
TRUNCATE TABLE "board_tables" CASCADE;
TRUNCATE TABLE "users" CASCADE;
TRUNCATE TABLE "roles" CASCADE;

-- reset sequence
SELECT SETVAL((SELECT PG_GET_SERIAL_SEQUENCE('"roles"', 'id')), 1, FALSE);

SELECT SETVAL((SELECT PG_GET_SERIAL_SEQUENCE('"categories"', 'id')), 1, FALSE);

COMMIT;